[plugins]
spotless = { id = "com.diffplug.spotless", version = "5.9.0" }
detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.19.0" }
kotlin_serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version = "1.4.30" }

[versions]
#kotlin = "1.4.30"
#google-dagger = "2.44"
#androidx-test-ext-junit = "1.1.3"
#androidx-test-espresso = "3.4.0"
#androidx-databinding = "7.3.1"
#kotlinx-coroutines = "1.6.1"
#kotlinx-serialization = "1.0.1"
#androidx-fragment = "1.5.4"

#google-android-material = "1.6.0"
#androidx-constraintlayout = "2.1.3"
#jakewharton-retrofit2-kotlinx-serialization-converter = "0.8.0"
#retrofit2 = "2.9.0"
#okhttp3 = "4.9.1"
#androidx-navigation = "2.4.2"
#androidx-lifecycle = "2.6.0-alpha03"
#androidx-datastore = "1.0.0"
#androidx-compose = "2022.10.00"
#androidx-activity = "1.5.1"
#androidx-lifecycle-viewmodel-compose = "2.5.1"
#coil-kt = "2.2.2"
#jakewharton-timber = "5.0.1"
#junit-junit = "4.13.2"
#androidx-compose-compiler = "1.3.2"
nstack = "3.2.9"
kotlin = "1.7.20"
kotlin_coroutines = "1.6.4"
retrofit = "2.9.0"
okhttp = "5.0.0-alpha.10"
compose = "1.3.1"
compose_compiler = "1.3.0-rc02"
hilt = "2.44.1"
lifecycle = "2.6.0-alpha03"
navigation = "2.4.2"
datastore = "1.0.0"
google-accompanist = "0.27.0"
androidx-appcompat = "1.4.1"
androidx-core = "1.7.0"

[libraries]
#-------------------------
# Kotlin
#-------------------------
kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin_gradle_plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin_coroutines_android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlin_coroutines" }
kotlin_coroutines_jdk = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "kotlin_coroutines" }
kotlin_coroutines_test = "org.jetbrains.kotlinx:kotlinx-coroutines-test:1.6.4"
kotlin_serialization_json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.4.1"
#-------------------------
# Android
#-------------------------
android_fragment = { module = "androidx.fragment:fragment-ktx", version = "1.5.4" }
android_material = { group = "com.google.android.material", name = "material", version = "1.6.0" }
android_contraint_layout = { group = "androidx.constraintlayout", name = "constraintlayout", version = "2.1.3" }
android_appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
android_core = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
#-------------------------
# Android - Lifecycle
#-------------------------
android_lifecycle_core = { module = "androidx.lifecycle:lifecycle-livedata-core-ktx", version.ref = "lifecycle" }
android_lifecycle_runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
android_lifecycle_common = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycle" }
android_lifecycle_viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
android_lifecycle_livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
android_lifecycle_viewmodel_compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
android_lifecycle_runtime_compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
#-------------------------
# Android - Hilt
#-------------------------
hilt_android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt_compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt_android_plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
#-------------------------
# Android - Compose
#-------------------------
android_compose_ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
android_compose_material = { module = "androidx.compose.material:material", version.ref = "compose" }
android_compose_ui_util = { module = "androidx.compose.ui:ui-util", version.ref = "compose" }
android_compose_ui_tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
android_compose_runtime = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose" }
andorid_compose_ui_test = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
android_compose_ui_test_manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
android_compose_material_windowsize = "androidx.compose.material3:material3-window-size-class:1.0.1"
compose_bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose" }
#-------------------------
# Android - Navigation
#-------------------------
android_navigation_fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
android_navigation_ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
android_navigation_compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
#-------------------------
# Android - DataStore
#-------------------------
android_datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
android_datastore_preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
#-------------------------
# Networking
#-------------------------
retrofit_converter = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:0.8.0"
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
okhttp_logger = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
okhttp_mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
#-------------------------
# NStack
#-------------------------
nstack = { module = "dk.nodes.nstack:nstack-kotlin", version.ref = "nstack" }
nstack_plugin = { module = "dk.nodes.nstack:translation", version.ref = "nstack" }
#-------------------------
# Accompanist
#-------------------------
accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "google-accompanist" }
accompanist-placeholder-material = { group = "com.google.accompanist", name = "accompanist-placeholder-material", version.ref = "google-accompanist" }
accompanist-pager = { group = "com.google.accompanist", name = "accompanist-pager", version.ref = "google-accompanist" }
#-------------------------
# Tests
#-------------------------
junit = { group = "junit", name = "junit", version = "4.13.2" }
junit_android = { group = "androidx.test.ext", name = "junit", version = "1.1.3" }
espresso_core = { group = "androidx.test.espresso", name = "espresso-core", version = "3.4.0" }
#-------------------------
# Others
#-------------------------
timber = { group = "com.jakewharton.timber", name = "timber", version = "5.0.1" }


#com-android-tools-build-gradle = "com.android.tools.build:gradle:7.3.1"
#kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
#translation = "dk.nodes.nstack:translation:3.2.5"
#hilt-android-gradle-plugin = { group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref = "google-dagger" }
#hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "google-dagger" }
#org-jacoco-ant = "org.jacoco:org.jacoco.ant:0.8.7"
#androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
#espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-test-espresso" }
#viewbinding = { group = "androidx.databinding", name = "viewbinding", version.ref = "androidx-databinding" }
#ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
#kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
#kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
#kotlinx-coroutines-jdk8 = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-jdk8", version.ref = "kotlinx-coroutines" }
#kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
#fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "androidx-fragment" }
#core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
#appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
#com-google-android-material-material = { group = "com.google.android.material", name = "material", version.ref = "google-android-material" }
#constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidx-constraintlayout" }
#hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "google-dagger" }
#retrofit2-kotlinx-serialization-converter = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "jakewharton-retrofit2-kotlinx-serialization-converter" }
#retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit2" }
#logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp3" }
#navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "androidx-navigation" }
#navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "androidx-navigation" }
#lifecycle-livedata-core-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-core-ktx", version.ref = "androidx-lifecycle" }
#lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
#lifecycle-common-java8 = { group = "androidx.lifecycle", name = "lifecycle-common-java8", version.ref = "androidx-lifecycle" }
#lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
#lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }
#lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
#datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "androidx-datastore" }
#compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidx-compose" }
#androidx-compose-material-material = { module = "androidx.compose.material:material" }
#ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
#material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
#activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity" }
#lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle-viewmodel-compose" }
#material3-window-size-class = { module = "androidx.compose.material3:material3-window-size-class" }
#coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil-kt" }
#accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "google-accompanist" }
#accompanist-placeholder-material = { group = "com.google.accompanist", name = "accompanist-placeholder-material", version.ref = "google-accompanist" }
#accompanist-pager = { group = "com.google.accompanist", name = "accompanist-pager", version.ref = "google-accompanist" }
#nstack-kotlin = "dk.nodes.nstack:nstack-kotlin:3.2.5"
#timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "jakewharton-timber" }
#junit-junit = { group = "junit", name = "junit", version.ref = "junit-junit" }
#androidx-compose-compiler-compiler = { group = "androidx.compose.compiler", name = "compiler", version.ref = "androidx-compose-compiler" }
#kotlin-annotation-processing-gradle = { group = "org.jetbrains.kotlin", name = "kotlin-annotation-processing-gradle", version.ref = "kotlin" }
#kotlin-serialization = { group = "org.jetbrains.kotlin", name = "kotlin-serialization", version.ref = "kotlin" }
