name: Build and Test

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Spotless Check
        run: ./gradlew spotlessCheck

      - name: Detekt Check
        run: ./gradlew detekt

      - name: Run Tests
        run: ./gradlew test
